In [368]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [369]:
lr=LogisticRegression(max_iter=1000)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9648148148148148

In [370]:
svm=SVC()
svm.fit(X_train, y_train)
svm.score(X_test,y_test)

0.9851851851851852

In [371]:
rf=RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9796296296296296

In [388]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [389]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [390]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [391]:
get_score(SVC(),X_train, X_test, y_train, y_test)

0.9851851851851852

In [392]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)
folds

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [416]:
score_lr=[]
score_svm=[]
score_rf=[]

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]

    score_lr.append(get_score(LogisticRegression(max_iter=1000), X_train, X_test, y_train, y_test))
    score_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=200), X_train, X_test, y_train, y_test))

In [409]:
score_lr

[0.9248747913188647, 0.9432387312186978, 0.9148580968280468]

In [410]:
score_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [411]:
score_rf

[0.9365609348914858, 0.9582637729549248, 0.9198664440734557]

In [414]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(max_iter=1000), digits.data, digits.target)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [417]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [418]:
cross_val_score(RandomForestClassifier(n_estimators=200), digits.data, digits.target)

array([0.92777778, 0.91666667, 0.96100279, 0.96935933, 0.91922006])